sequenceDiagram
actor AA as Admin/Almoxarifado
AA ->> ItemListaMaterialCotacaoAction : buscarListaMaterialComCotacao
activate ItemListaMaterialCotacaoAction
ItemListaMaterialCotacaoAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32 
deactivate ItemDAO
ItemService -->> ItemListaMaterialCotacaoAction : #32
deactivate ItemService
ItemListaMaterialCotacaoAction ->> ItemService : getItem
activate ItemService
ItemService ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaMaterialCotacaoAction : #32; 
deactivate ItemService
ItemListaMaterialCotacaoAction ->> ItemService : getListaMaterial
activate ItemService
ItemService ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaMaterialCotacaoAction : #32; 
deactivate ItemService
ItemListaMaterialCotacaoAction ->> ItemService : getListaMaterial
activate ItemService
ItemService ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaMaterialCotacaoAction : #32; 
deactivate ItemService
ItemListaMaterialCotacaoAction ->> ItemService : getCotacaoItem
activate ItemService
ItemService ->> ItemDAO : getCotacaoItem
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItem
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaMaterialCotacaoAction : #32; 
deactivate ItemService
deactivate ItemListaMaterialCotacaoAction
