sequenceDiagram
actor AA as Almoxarifado/Admin
AA ->> ItemBuscaItemAction : buscarItem
activate ItemBuscaItemAction
ItemBuscaItemAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemBuscaItemAction : #32; 
deactivate ItemService
ItemBuscaItemAction ->> ItemService : getItensById
activate ItemService
ItemService ->> ItemDAO : getItensById
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemBuscaItemAction : #32; 
deactivate ItemService
deactivate ItemBuscaItemAction

opt Busca por Item Fabricado
    AA ->> ItemBuscaItemAction : buscarItemFabricado
    activate ItemBuscaItemAction
    ItemBuscaItemAction ->> ItemService : new
    activate ItemService
    ItemService ->> ItemDAO : new
    activate ItemDAO
    ItemDAO -->> ItemService : #32; 
    deactivate ItemDAO
    ItemService -->> ItemBuscaItemAction : #32; 
    deactivate ItemService
    ItemBuscaItemAction ->> ItemService : getItensFabricadoById
    activate ItemService
    ItemService ->> ItemDAO : getItensFabriacadosById
    activate ItemDAO
    ItemDAO -->> ItemService : #32; 
    deactivate ItemDAO
    ItemService -->> ItemBuscaItemAction : #32; 
    deactivate ItemService
    deactivate ItemBuscaItemAction
end
