sequenceDiagram
actor AA as Almoxarifado/Admin
AA ->> ItemBuscaItemAction : buscarItem (Item, Insumo, Origem)
activate ItemBuscaItemAction
ItemBuscaItemAction ->> ItemService : new (idItem, idInsumo, origem)
activate ItemService
ItemService ->> ItemDAO : new (idItem, idInsumo, origem)
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemBuscaItemAction : #32; 
deactivate ItemService
ItemBuscaItemAction ->> ItemService : getItensById(parteIdItem)
activate ItemService
ItemService ->> ItemDAO : getItensById(parteIdItem)
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemBuscaItemAction : #32; 
deactivate ItemService
deactivate ItemBuscaItemAction

opt Busca por Item Fabricado
    AA ->> ItemBuscaItemAction : buscarItemFabricado (Item, Insumo, Origem)
    activate ItemBuscaItemAction
    ItemBuscaItemAction ->> ItemService : new (idItem, idInsumo, origem)
    activate ItemService
    ItemService ->> ItemDAO : new (idItem, idInsumo, origem)
    activate ItemDAO
    ItemDAO -->> ItemService : #32; 
    deactivate ItemDAO
    ItemService -->> ItemBuscaItemAction : #32; 
    deactivate ItemService
    ItemBuscaItemAction ->> ItemService : getItensFabricadoById(parteIdItem)
    activate ItemService
    ItemService ->> ItemDAO : getItensFabriacadosById(parteIdItem)
    activate ItemDAO
    ItemDAO -->> ItemService : #32; 
    deactivate ItemDAO
    ItemService -->> ItemBuscaItemAction : #32; 
    deactivate ItemService
    deactivate ItemBuscaItemAction
end
