sequenceDiagram
actor AA as Admin/Almoxarifado
AA ->> ItemBuscaValorizacaoAction : buscarItensComCotacao (Item, Nome Item)
activate ItemBuscaValorizacaoAction
ItemBuscaValorizacaoAction ->> ItemService : new (idItem, nomeItem)
activate ItemService
ItemService ->> ItemDAO : new (idItem, nomeItem)
activate ItemDAO
ItemDAO -->> ItemService : #32 
deactivate ItemDAO
ItemService -->> ItemBuscaValorizacaoAction : #32 
deactivate ItemService
ItemBuscaValorizacaoAction ->> ItemService : getItensComCotacao(idItem,nomeItem,possuiNrSerie,possuiListaMaterial,ativo)
activate ItemService
ItemService ->> ItemService : getItens
activate ItemService
ItemService ->> ItemDAO : getItens(idItem,nomeItem,possuiNrSerie,possuiListaMaterial,ativo)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemService : #32 
deactivate ItemDAO
ItemService -->> ItemService : #32 
deactivate ItemService
ItemService ->> ItemDAO : getCotacaoItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32
deactivate ItemDAO
ItemDAO -->> ItemService : #32 
deactivate ItemDAO
ItemService -->> ItemBuscaValorizacaoAction : #32
deactivate ItemService
ItemBuscaValorizacaoAction ->> BranqsSupport : RecuperarDouble2CasasDecimais(n)
activate BranqsSupport
BranqsSupport -->> ItemBuscaValorizacaoAction : #32
deactivate BranqsSupport
ItemBuscaValorizacaoAction ->> BranqsSupport : RecuperarDouble2CasasDecimais(n)
activate BranqsSupport
BranqsSupport -->> ItemBuscaValorizacaoAction : #32 
deactivate BranqsSupport
ItemBuscaValorizacaoAction ->> BranqsSupport : RecuperarMonetarioBr(n)
activate BranqsSupport
BranqsSupport -->> ItemBuscaValorizacaoAction : #32 
deactivate BranqsSupport
ItemBuscaValorizacaoAction ->> BranqsSupport : RecuperarMonetarioBr(n)
activate BranqsSupport
BranqsSupport -->> ItemBuscaValorizacaoAction : #32
deactivate BranqsSupport
ItemBuscaValorizacaoAction ->> BranqsSupport : RecuperarNumeroBr(n)
activate BranqsSupport
BranqsSupport -->> ItemBuscaValorizacaoAction : #32
deactivate BranqsSupport
ItemBuscaValorizacaoAction ->> BranqsSupport : RecuperarMonetarioBr(n)
activate BranqsSupport
BranqsSupport -->> ItemBuscaValorizacaoAction : #32
deactivate BranqsSupport
deactivate ItemBuscaValorizacaoAction
 

