sequenceDiagram
actor EA as Engenheiro/Admin
EA ->> ItemAction : inserir (Item, Nome Item)
activate ItemAction
ItemAction ->> ItemAction : validar_Inserir
activate ItemAction
deactivate ItemAction
ItemAction ->> ItemService : new (idItem, nomeItem)
activate ItemService
ItemService ->> ItemDAO : new (idItem, nomeItem)
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemService
deactivate ItemDAO
ItemAction ->> ItemService : getListaMaterial
activate ItemService
ItemService ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemAction : #32; 
deactivate ItemService
ItemAction ->> ItemService : inserir
activate ItemService
ItemService ->> ItemDAO : inserir
activate ItemDAO
ItemDAO ->> ItemDAO : atualizaListaMateriais
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemAction : #32; 
deactivate ItemService
deactivate ItemAction
