sequenceDiagram
actor EA as Engenheiro/Admin
EA ->> ItemAction : inserir(idItem, nomeItem, ultimoFornecedor, prazoEntrega, impostos, partNumber, frete, possuiNrSerie, ativo, qtdeMinEstoque, unidade, itemADuplicar)
activate ItemAction
ItemAction ->> ItemAction : validar_Inserir
activate ItemAction
deactivate ItemAction
ItemAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new 
activate ItemDAO
ItemDAO -->> ItemService : #32;
deactivate ItemDAO 
ItemService-->>ItemAction: 
deactivate ItemService
ItemAction ->> ItemService : getListaMaterial(idItem)
activate ItemService
ItemService ->> ItemDAO : getListaMaterial(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
deactivate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
ItemDAO -->> ItemService : Material 
deactivate ItemDAO
ItemService -->> ItemAction : Material
deactivate ItemService
ItemAction ->> ItemService : inserir(item)
activate ItemService
ItemService ->> ItemDAO : inserir(item)
activate ItemDAO
ItemDAO ->> ItemDAO : atualizaListaMateriais(item)
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemAction : #32; 
deactivate ItemService
deactivate ItemAction
