sequenceDiagram
actor AA as Admin/Almoxarifado
AA ->> ItemListaAction : pesquisarItens
activate ItemListaAction
ItemListaAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaAction : #32; 
deactivate ItemService
ItemListaAction ->> ItemService : getItens
activate ItemService
ItemService ->> ItemDAO : getItens
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaAction : #32; 
deactivate ItemService
deactivate ItemListaAction
