sequenceDiagram
actor EA as Engenheiro/Admin
EA ->> ItemCotacoesAction : pesquisarCotacoes
activate ItemCotacoesAction
ItemCotacoesAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemCotacoesAction : #32; 
deactivate ItemService
ItemCotacoesAction ->> ItemService : getItem
activate ItemService
ItemService ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemCotacoesAction : #32; 
deactivate ItemService
ItemCotacoesAction ->> ItemService : getCotacoes
activate ItemService
ItemService ->> ItemDAO : getCotacoes
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemCotacoesAction : #32; 
deactivate ItemService
deactivate ItemCotacoesAction
