sequenceDiagram
actor User
User ->> ItemListaAction : pesquisarItens
activate ItemListaAction
ItemListaAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaAction : #32; 
deactivate ItemService
ItemListaAction ->> ItemService : getItens
activate ItemService
ItemService ->> ItemDAO : getItens
activate ItemDAO
ItemDAO ->> Item : new
activate Item
Item -->> ItemDAO : #32; 
deactivate Item
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO ->> Cotacao : new
activate Cotacao
Cotacao -->> ItemDAO : #32; 
deactivate Cotacao
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> ItemDAO : getItem
activate ItemDAO
ItemDAO ->> Item : new
activate Item
Item -->> ItemDAO : #32; 
deactivate Item
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> Material : new
activate Material
Material -->> ItemDAO : #32; 
deactivate Material
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaAction : #32; 
deactivate ItemService
deactivate ItemListaAction
