sequenceDiagram
actor AA as Admin/Almoxarifado
AA ->> ItemListaAction : pesquisarItens (Item, Nome)
activate ItemListaAction
ItemListaAction ->> ItemService : new (idItem, nomeItem)
activate ItemService
ItemService ->> ItemDAO : new (idItem, nomeItem)
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaAction : #32; 
deactivate ItemService
ItemListaAction ->> ItemService : getItens(idItem)
activate ItemService
ItemService ->> ItemDAO : getItens(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> ItemDAO : getListaMaterial(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
activate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemListaAction : #32; 
deactivate ItemService
deactivate ItemListaAction
