sequenceDiagram
actor EA as Engenheiro/Admin
EA ->> ItemCotacoesAction : pesquisarCotacoes (Item)
activate ItemCotacoesAction
ItemCotacoesAction ->> ItemService : new (idItem)
activate ItemService
ItemService ->> ItemDAO : new (idItem)
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemCotacoesAction : #32; 
deactivate ItemService
ItemCotacoesAction ->> ItemService : getItem(idItem)
activate ItemService
ItemService ->> ItemDAO : getItem(idItem)
activate ItemDAO
ItemDAO ->> ItemDAO : getCotacaoItemComprado(idItem)
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemCotacoesAction : #32; 
deactivate ItemService
ItemCotacoesAction ->> ItemService : getCotacoes(idItem)
activate ItemService
ItemService ->> ItemDAO : getCotacoes(idItem)
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemCotacoesAction : #32; 
deactivate ItemService
deactivate ItemCotacoesAction
