sequenceDiagram
actor User
User ->> ItemBuscaItemAction : buscarItemFabricado
activate ItemBuscaItemAction
ItemBuscaItemAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemBuscaItemAction : #32; 
deactivate ItemService
ItemBuscaItemAction ->> ItemService : getItensFabricadoById
activate ItemService
ItemService ->> ItemDAO : getItensFabriacadosById
activate ItemDAO
ItemDAO ->> Item : new
activate Item
Item -->> ItemDAO : #32; 
deactivate Item
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemBuscaItemAction : #32; 
deactivate ItemService
deactivate ItemBuscaItemAction
