sequenceDiagram
actor User
User ->> ProjecaoComprasRelAction : projetarComprasLote
activate ProjecaoComprasRelAction
ProjecaoComprasRelAction ->> ProjecaoComprasRelAction : validar_projetarComprasLote
activate ProjecaoComprasRelAction
ProjecaoComprasRelAction -->> ProjecaoComprasRelAction : #32; 
deactivate ProjecaoComprasRelAction
ProjecaoComprasRelAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ProjecaoComprasRelAction : #32; 
deactivate ItemService
ProjecaoComprasRelAction ->> ItemService : somarInsumoListaPrincipal
activate ItemService
ItemService ->> ItemService : getListaMaterial
activate ItemService
ItemService ->> ItemDAO : getListaMaterial
activate ItemDAO
ItemDAO ->> Item : new
activate Item
Item -->> ItemDAO : #32; 
deactivate Item
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO ->> Cotacao : new
activate Cotacao
Cotacao -->> ItemDAO : #32; 
deactivate Cotacao
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO ->> Material : new
activate Material
Material -->> ItemDAO : #32; 
deactivate Material
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ItemService : #32; 
deactivate ItemService
ItemService -->> ProjecaoComprasRelAction : #32; 
deactivate ItemService
ProjecaoComprasRelAction ->> ItemService : getQtdeAComprar
activate ItemService
ItemService -->> ProjecaoComprasRelAction : #32; 
deactivate ItemService
ProjecaoComprasRelAction ->> ItemService : getItensAComprar
activate ItemService
ItemService ->> ItemDAO : getItensAComprar
activate ItemDAO
ItemDAO ->> Item : new
activate Item
Item -->> ItemDAO : #32; 
deactivate Item
ItemDAO ->> ItemDAO : getCotacaoItemComprado
activate ItemDAO
ItemDAO ->> Cotacao : new
activate Cotacao
Cotacao -->> ItemDAO : #32; 
deactivate Cotacao
ItemDAO -->> ItemDAO : #32; 
deactivate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ProjecaoComprasRelAction : #32; 
deactivate ItemService
ProjecaoComprasRelAction ->> Material : new
activate Material
Material -->> ProjecaoComprasRelAction : #32; 
deactivate Material
ProjecaoComprasRelAction ->> ItemService : OrdenarFornecedorEPrazoEntrega
activate ItemService
ItemService -->> ProjecaoComprasRelAction : #32; 
deactivate ItemService
ProjecaoComprasRelAction ->> ItemService : getQtdeAComprar
activate ItemService
ItemService -->> ProjecaoComprasRelAction : #32; 
deactivate ItemService
deactivate ProjecaoComprasRelAction
