sequenceDiagram
actor A as Admin
A ->> UsuarioAction : atualizarUsuario
activate UsuarioAction
UsuarioAction ->> UsuarioAction : validar_AtualizarUsuario
activate UsuarioAction
UsuarioAction -->> UsuarioAction : #32; 
deactivate UsuarioAction
UsuarioAction ->> UsuarioService : new
activate UsuarioService
UsuarioService ->> UsuarioDAO : new
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
UsuarioAction ->> UsuarioService : atualizar
activate UsuarioService
UsuarioService ->> UsuarioDAO : atualizar
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
deactivate UsuarioAction
