sequenceDiagram
actor A as Admin
A ->> UsuarioBuscaAction : buscarUsuario
activate UsuarioBuscaAction
UsuarioBuscaAction ->> UsuarioService : new
activate UsuarioService
UsuarioService ->> UsuarioDAO : new
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioBuscaAction : #32; 
deactivate UsuarioService
UsuarioBuscaAction ->> UsuarioService : getUsuarios
activate UsuarioService
UsuarioService ->> UsuarioDAO : getUsuarios
activate UsuarioDAO
UsuarioDAO ->> UsuarioDAO : getUsuario
activate UsuarioDAO
UsuarioDAO ->> UsuarioDAO : getPerfil
activate UsuarioDAO
UsuarioDAO -->> UsuarioDAO : #32; 
deactivate UsuarioDAO
UsuarioDAO -->> UsuarioDAO : #32; 
deactivate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioBuscaAction : #32; 
deactivate UsuarioService
deactivate UsuarioBuscaAction
