sequenceDiagram
actor User
User ->> UsuarioBuscaAction : buscarUsuario
activate UsuarioBuscaAction
UsuarioBuscaAction ->> UsuarioService : new
activate UsuarioService
UsuarioService ->> UsuarioDAO : new
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioBuscaAction : #32; 
deactivate UsuarioService
UsuarioBuscaAction ->> UsuarioService : getUsuarios
activate UsuarioService
UsuarioService ->> UsuarioDAO : getUsuarios
activate UsuarioDAO
UsuarioDAO ->> Perfil : new
activate Perfil
Perfil -->> UsuarioDAO : #32; 
deactivate Perfil
UsuarioDAO ->> UsuarioDAO : getUsuario
activate UsuarioDAO
UsuarioDAO ->> Usuario : new
activate Usuario
Usuario -->> UsuarioDAO : #32; 
deactivate Usuario
UsuarioDAO ->> Perfil : new
activate Perfil
Perfil -->> UsuarioDAO : #32; 
deactivate Perfil
UsuarioDAO ->> UsuarioDAO : getPerfil
activate UsuarioDAO
UsuarioDAO ->> Perfil : new
activate Perfil
Perfil -->> UsuarioDAO : #32; 
deactivate Perfil
UsuarioDAO -->> UsuarioDAO : #32; 
deactivate UsuarioDAO
UsuarioDAO -->> UsuarioDAO : #32; 
deactivate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioBuscaAction : #32; 
deactivate UsuarioService
deactivate UsuarioBuscaAction
