sequenceDiagram
actor A as Admin
A ->> UsuarioAction : editUsuario (idUsuario)
activate UsuarioAction
UsuarioAction ->> UsuarioService : new (idUsuario)
activate UsuarioService
UsuarioService ->> UsuarioDAO : new (idUsuario)
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
UsuarioAction ->> UsuarioService : getUsuario
activate UsuarioService
UsuarioService ->> UsuarioDAO : getUsuario
activate UsuarioDAO
UsuarioDAO ->> UsuarioDAO : getPerfil
activate UsuarioDAO
UsuarioDAO -->> UsuarioDAO : #32; 
deactivate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
deactivate UsuarioAction
