sequenceDiagram
actor A as Admin
A ->> UsuarioAction : inserirUsuario
activate UsuarioAction
UsuarioAction ->> UsuarioAction : validar_InserirUsuario
activate UsuarioAction
UsuarioAction ->> UsuarioService : new
activate UsuarioService
UsuarioService ->> UsuarioDAO : new
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
UsuarioAction ->> UsuarioService : getUsuario
activate UsuarioService
UsuarioService ->> UsuarioDAO : getUsuario
activate UsuarioDAO
UsuarioDAO ->> UsuarioDAO : getPerfil
activate UsuarioDAO
UsuarioDAO -->> UsuarioDAO : #32; 
deactivate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
UsuarioAction -->> UsuarioAction : #32; 
deactivate UsuarioAction
UsuarioAction ->> UsuarioService : new
activate UsuarioService
UsuarioService ->> UsuarioDAO : new
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
UsuarioAction ->> UsuarioService : inserir
activate UsuarioService
UsuarioService ->> UsuarioDAO : inserir
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> UsuarioAction : #32; 
deactivate UsuarioService
deactivate UsuarioAction
