sequenceDiagram
actor User
User ->> MovimentacaoAction : adicionarMateriaisNoEstoque
activate MovimentacaoAction
MovimentacaoAction ->> MovimentacaoAction : validar_AdicionarMateriaisNoEstoque
activate MovimentacaoAction
MovimentacaoAction ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> MovimentacaoAction : #32; 
deactivate ItemService
MovimentacaoAction ->> ItemService : existeItemComNrSerieEmEstoque(idItem,nrSerie)
activate ItemService
ItemService ->> MovimentacaoService : new
activate MovimentacaoService
MovimentacaoService ->> MovimentacaoDAO : new
activate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoService : #32; 
deactivate MovimentacaoDAO
MovimentacaoService -->> ItemService : #32; 
deactivate MovimentacaoService
ItemService ->> MovimentacaoService : getMovimentacoes(idItem,nrSerie)
activate MovimentacaoService
MovimentacaoService ->> MovimentacaoDAO : getMovimentacoes(idItem,nrSerie)
activate MovimentacaoDAO
MovimentacaoDAO ->> ItemService : new
activate ItemService
ItemService -->> MovimentacaoDAO : #32; 
deactivate ItemService
MovimentacaoDAO ->> MovimentacaoDAO : getMovimentacao(idMovimentacao)
activate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoDAO : #32; 
deactivate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoService : #32; 
deactivate MovimentacaoDAO
MovimentacaoService -->> ItemService : #32; 
deactivate MovimentacaoService
ItemService -->> MovimentacaoAction : #32; 
deactivate ItemService
MovimentacaoAction -->> MovimentacaoAction : #32; 
deactivate MovimentacaoAction
MovimentacaoAction ->> MovimentacaoService : new
activate MovimentacaoService
MovimentacaoService ->> MovimentacaoDAO : new
activate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoService : #32; 
deactivate MovimentacaoDAO
MovimentacaoService -->> MovimentacaoAction : #32; 
deactivate MovimentacaoService
MovimentacaoAction ->> MovimentacaoService : adicionarNoEstoque(Movimentacao)
activate MovimentacaoService
MovimentacaoService ->> MovimentacaoDAO : adicionarNoEstoque(Movimentacao)
activate MovimentacaoDAO
MovimentacaoDAO ->> MovimentacaoDAO : movimentar(Movimentacao)
activate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoDAO : #32; 
deactivate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoService : #32; 
deactivate MovimentacaoDAO
MovimentacaoService -->> MovimentacaoAction : #32; 
deactivate MovimentacaoService
deactivate MovimentacaoAction
