sequenceDiagram
actor User
User ->> MovimentacaoHistoricoAction : buscarMovimentacoes
activate MovimentacaoHistoricoAction
MovimentacaoHistoricoAction ->> MovimentacaoHistoricoAction : validar_buscarMovimentacoes
activate MovimentacaoHistoricoAction
MovimentacaoHistoricoAction -->> MovimentacaoHistoricoAction : #32; 
deactivate MovimentacaoHistoricoAction
MovimentacaoHistoricoAction ->> MovimentacaoService : new
activate MovimentacaoService
MovimentacaoService ->> MovimentacaoDAO : new
activate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoService : #32; 
deactivate MovimentacaoDAO
MovimentacaoService -->> MovimentacaoHistoricoAction : #32; 
deactivate MovimentacaoService
MovimentacaoHistoricoAction ->> MovimentacaoService : getMovimentacoes
activate MovimentacaoService
MovimentacaoService ->> MovimentacaoDAO : getMovimentacoes
activate MovimentacaoDAO
MovimentacaoDAO ->> MovimentacaoDAO : getMovimentacao
activate MovimentacaoDAO
MovimentacaoDAO ->> ItemService : new
activate ItemService
ItemService ->> ItemDAO : new
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> MovimentacaoDAO : #32; 
deactivate ItemService
MovimentacaoDAO ->> ItemService : getItem
activate ItemService
ItemService ->> ItemDAO : getItem
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> MovimentacaoDAO : #32; 
deactivate ItemService
MovimentacaoDAO ->> Material : new
activate Material
Material -->> MovimentacaoDAO : #32; 
deactivate Material
MovimentacaoDAO ->> UsuarioService : new
activate UsuarioService
UsuarioService ->> UsuarioDAO : new
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> MovimentacaoDAO : #32; 
deactivate UsuarioService
MovimentacaoDAO ->> UsuarioService : getUsuario
activate UsuarioService
UsuarioService ->> UsuarioDAO : getUsuario
activate UsuarioDAO
UsuarioDAO -->> UsuarioService : #32; 
deactivate UsuarioDAO
UsuarioService -->> MovimentacaoDAO : #32; 
deactivate UsuarioService
MovimentacaoDAO -->> MovimentacaoDAO : #32; 
deactivate MovimentacaoDAO
MovimentacaoDAO -->> MovimentacaoService : #32; 
deactivate MovimentacaoDAO
MovimentacaoService -->> MovimentacaoHistoricoAction : #32; 
deactivate MovimentacaoService
deactivate MovimentacaoHistoricoAction
