sequenceDiagram
actor CA as Compras/Admin
CA ->> ProjecaoComprasAction : removerMateriaisFabricadoDoLote(materialFabLote, listaIdItem)
activate ProjecaoComprasAction
ProjecaoComprasAction ->> ProjecaoComprasAction : validar_RemoverMateriaisFabricadoDoLote 
activate ProjecaoComprasAction
ProjecaoComprasAction -->> ProjecaoComprasAction : #32; 
deactivate ProjecaoComprasAction
ProjecaoComprasAction ->> ItemService : new (materialFabLote, listaIdItem)
activate ItemService
ItemService ->> ItemDAO : new (materialFabLote, listaIdItem)
activate ItemDAO
ItemDAO -->> ItemService : #32; 
deactivate ItemDAO
ItemService -->> ProjecaoComprasAction : #32; 
deactivate ItemService
ProjecaoComprasAction ->> ItemService : removerMateriaisFabricadoDoLote(materialFabLote, listaIdItem)
activate ItemService
ItemService -->> ProjecaoComprasAction : #32; 
deactivate ItemService
deactivate ProjecaoComprasAction
